### PR TITLE
Issue210 language highlight

### PR DESCRIPTION
**Pull request by guotin**
@jakekall and I Got the robot language syntax highlighting working with textmate. Seems to highlight quite nicely. Tested locally in development and production mode. 

Issues:
* Code is kind of hard to understand
  * Comments from the authors of [original demo project](https://github.com/bolinfest/monaco-tm) left inside the code 
* Editor is always set to dark mode because the robot theme is build on "vscode-dark"
  * Issue #214 
* Syntax highlighting sometimes "laggs". Clicking something on the page gets it working.

### CODE REVIEW

**Comment by att78** [comment]
I tested this a bit this morning. Just a note regarding lagging: I could not repeat lagging. Is it possible, that lagging was caused by lack of virtual memory when run locally rather than problem in a code?  

Everything seemed to work ok and the dark mode fix is already main topic for issue 214.

**Review by att78 — APPROVED** [review]

**Comment by guotin** [comment]
Don't know what might cause it but refreshing the page manually while editing a file (page url like `http://localhost:3000/edit?q=ohtuprojekti-eficode/robot-test-files/example.txt`) causes it for me, sometimes.

**Comment by att78** [comment]
good point about refreshing. Refreshing did not cause lagging when I tried, but made the whole dark mode vanish. I got it back by toggling darkmode switch back and forth.

**Review by ilkkamaksy — APPROVED** [review]
Excellent, lgtm

**Pull request merged**
