### PR TITLE
Issue227 reduce redirects

### LINKED ISSUE #227: Reduce redirects when connecting to GitHub
When user connects to GitHub there are two redirects which doesn't look good. Atleast the second one could probably be done with React Router's [useHistory](https://reactrouter.com/web/api/Hooks/usehistory) hook.

### PR DESCRIPTION
**Pull request by jakekall**
Closes #227 
- After a successful connect, the view is now changed smoothly with `useHistory` hook
    - Now goes to edit view instead since going to main menu didn't make much sense
- Noticed that few of the queries were missing types for the return values so I added them in
- Fixed the capitalization of two types and removed unnecessary id field from `UserType` since it was never returned from the query anyway

### CODE REVIEW

**Review by ilkkamaksy — COMMENTED** [review]
can you rebase to staging before merging?

**Comment by guotin** [comment]
I tried this and it seems that because the `App.tsx` is not re-rendered anymore, the `user` doesn't update.

I console logged the frontend `user` in `App.tsx` and got the following:

1. Register to application -> registered, logged in and forwarded to the  main page. User is console logged correctly
2. Connect github with the button -> it works and page is redirected to edit view but now the `App.tsx` is not rendered again and the user still has services as `null`. Refreshing the page manually results in refresh of whole application and console logged user has the correct services list. This doesn't really affect our scenario at the moment because the commit details are not taken from the ServiceUser list but it might be a problem in the future.

What do you think? The main change here is that the user is not in the same state as before in frontend and it's sort of invisible at the moment.

**Comment by jakekall** [comment]
Adding `refetchQueries: [{ query: ME }]` to `addService` seems to fix this. I think that would be better than relying on the redirect to refresh our state.

Btw as I was testing this I noticed that we have a `UNIQUE(services_id, username))` on the `SERVICE_USERS` table which prevents the same GitHub account from being linked to multiple different users but they still get the token and can push with it which is a bit weird.

**Review by guotin — APPROVED** [review]
Yes way better now. Nice fix. I remember trying to refetch the query in the registerform but I probably did something silly.

**Comment by guotin** [comment]
And let's add the unique database constraint problem to our documentation as a problem

**Review by ilkkamaksy — APPROVED** [review]
👍👍

**Pull request merged**
